# Generated by Django 4.0.4 on 2022-04-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
    ]
